#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("BeFreeAPP.Resource", IsApplication=true)]

namespace BeFreeAPP
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Befree_logo = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060010
			public const int SearchToolbar = 2131099664;
			
			// aapt resource value: 0x7f060011
			public const int ServiceView = 2131099665;
			
			// aapt resource value: 0x7f06000c
			public const int btnCreateAccount = 2131099660;
			
			// aapt resource value: 0x7f060005
			public const int btnCriarContaEfetiva = 2131099653;
			
			// aapt resource value: 0x7f06000b
			public const int btnLogIn = 2131099659;
			
			// aapt resource value: 0x7f060009
			public const int btnLogin = 2131099657;
			
			// aapt resource value: 0x7f06001a
			public const int btnServiceAnuncioComprar = 2131099674;
			
			// aapt resource value: 0x7f06001b
			public const int btnServiceAnuncioDenunciar = 2131099675;
			
			// aapt resource value: 0x7f06001c
			public const int btnServiceAnuncioVoltar = 2131099676;
			
			// aapt resource value: 0x7f060020
			public const int btnServiceBuscaComprar = 2131099680;
			
			// aapt resource value: 0x7f060021
			public const int btnServiceBuscaDenunciar = 2131099681;
			
			// aapt resource value: 0x7f060022
			public const int btnServiceBuscaVoltar = 2131099682;
			
			// aapt resource value: 0x7f060002
			public const int edtCriarContaCPF = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int edtCriarContaEmail = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int edtCriarContaNome = 2131099648;
			
			// aapt resource value: 0x7f060003
			public const int edtCriarContaSenha = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int edtCriarContaSenhaConf = 2131099652;
			
			// aapt resource value: 0x7f060008
			public const int edtSenha = 2131099656;
			
			// aapt resource value: 0x7f060006
			public const int edtUsuario = 2131099654;
			
			// aapt resource value: 0x7f060012
			public const int linearLayout1 = 2131099666;
			
			// aapt resource value: 0x7f060017
			public const int linearLayout2 = 2131099671;
			
			// aapt resource value: 0x7f060019
			public const int linearLayout3 = 2131099673;
			
			// aapt resource value: 0x7f06000d
			public const int progressBar1 = 2131099661;
			
			// aapt resource value: 0x7f060027
			public const int sample_content_fragment = 2131099687;
			
			// aapt resource value: 0x7f060026
			public const int sample_main_layout = 2131099686;
			
			// aapt resource value: 0x7f06000e
			public const int sliding_tabs = 2131099662;
			
			// aapt resource value: 0x7f060007
			public const int textView1 = 2131099655;
			
			// aapt resource value: 0x7f060013
			public const int textView2 = 2131099667;
			
			// aapt resource value: 0x7f060016
			public const int textView5 = 2131099670;
			
			// aapt resource value: 0x7f06000a
			public const int txtCreateAccount = 2131099658;
			
			// aapt resource value: 0x7f060018
			public const int txtServiceAnuncioDescricao = 2131099672;
			
			// aapt resource value: 0x7f060014
			public const int txtServiceAnuncioSubCategoria = 2131099668;
			
			// aapt resource value: 0x7f060015
			public const int txtServiceAnuncioTitulo = 2131099669;
			
			// aapt resource value: 0x7f06001f
			public const int txtServiceBuscaDescricao = 2131099679;
			
			// aapt resource value: 0x7f06001d
			public const int txtServiceBuscaSubCategoria = 2131099677;
			
			// aapt resource value: 0x7f06001e
			public const int txtServiceBuscaTitulo = 2131099678;
			
			// aapt resource value: 0x7f060025
			public const int txtServiceListDescricao = 2131099685;
			
			// aapt resource value: 0x7f060023
			public const int txtServiceListSubCategoria = 2131099683;
			
			// aapt resource value: 0x7f060024
			public const int txtServiceListTitulo = 2131099684;
			
			// aapt resource value: 0x7f06000f
			public const int viewpager = 2131099663;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int CriarConta = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Login = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Service = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int ServiceAnuncio = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int ServiceBusca = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int ServiceList = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int SlideMain = 2130903047;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int CustomActionBarTheme = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int MyActionBar = 2131034113;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
